// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OBNNPJe1eWvrWPqx5yB-Y0zjy04tfG8',
    appId: '1:1060127379340:web:3f4c8871cbb32acc8550a9',
    messagingSenderId: '1060127379340',
    projectId: 'testflutter-368d4',
    authDomain: 'testflutter-368d4.firebaseapp.com',
    storageBucket: 'testflutter-368d4.appspot.com',
    measurementId: 'G-WPSWSSTFXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98P9ig7Jiz5JcdZPCm0011ICzNHbTfJY',
    appId: '1:1060127379340:android:268b9fee87cc7edb8550a9',
    messagingSenderId: '1060127379340',
    projectId: 'testflutter-368d4',
    storageBucket: 'testflutter-368d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUvLhUZGFm8pe8QPF0MiVVKCCOQqyglsQ',
    appId: '1:1060127379340:ios:9df604e985bfe2808550a9',
    messagingSenderId: '1060127379340',
    projectId: 'testflutter-368d4',
    storageBucket: 'testflutter-368d4.appspot.com',
    iosClientId: '1060127379340-d2qq4cobqo6otntqerll0f8kec7pc325.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUvLhUZGFm8pe8QPF0MiVVKCCOQqyglsQ',
    appId: '1:1060127379340:ios:9df604e985bfe2808550a9',
    messagingSenderId: '1060127379340',
    projectId: 'testflutter-368d4',
    storageBucket: 'testflutter-368d4.appspot.com',
    iosClientId: '1060127379340-d2qq4cobqo6otntqerll0f8kec7pc325.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutter',
  );
}
